In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
# pd.set_option()

In [2]:
df = pd.read_csv("educational-facilities-in-nigeria (1).csv", low_memory=False)
df

,facility_name,facility_type_display,improved_water_supply,improved_sanitation,chalkboard_each_classroom_yn,num_tchrs_with_nce,num_tchr_full_time,num_students_total,num_classrms_total,phcn_electricity,num_toilets_total,num_students_male,num_students_female,num_tchrs_male,num_tchrs_female,date_of_survey,education_type,facility_id,community,ward,management,sector,formhub_photo_id,gps,survey_id,unique_lga,latitude,longitude
0,CPS SWALI,Primary school only,True,True,False,9.0,9.0,776.0,12.0,False,21.0,383.0,393.0,5.0,4.0,04/03/2014,formal_only,EIRJK,Swali,3,public,education,1393404015008.jpg,4.91691036 6.27412844 31.5 5.0,51885096-65a1-4f1f-8c2a-3b11d9ae40bb,bayelsa_yenagoa,4.916910,6.274128
1,NANA Basic Academy,Primary and Junior Secondary school combined,False,False,NaN,NaN,NaN,NaN,NaN,False,0.0,NaN,NaN,NaN,NaN,02/05/2014,formal_only,ENQHE,Mpape,Dutse,private,education,1396960914896.jpg,9.140918333333333 7.496761666666667 697.0 4.5,7f3ea41a-e4cb-41dd-85fc-5fa54c42d09f,fct_bwari,9.140918,7.496762
2,L.E.A Primary School Pabeyi,Primary school only,True,True,False,9.0,11.0,283.0,9.0,False,2.0,185.0,98.0,9.0,2.0,02/05/2014,formal_only,EDJJK,Pabeyi,Dobi,public,education,1397575395444.jpg,9.174855 7.0220616666666675 236.8 5.0,56f2e625-ec43-4c39-97a8-d6379dceefa2,fct_gwagwalada,9.174855,7.022062
3,L.E.A.PrimarySchoolPagadna,Primary school only,False,True,False,4.0,5.0,247.0,7.0,False,2.0,147.0,100.0,5.0,0.0,25/04/2014,formal_only,ELOOD,Pagadna,Dobi,public,education,1398262573409.jpg,9.115846666666666 6.962314999999999 216.5 4.4,2932eda8-64b1-4068-8412-3b2e099062fc,fct_gwagwalada,9.115847,6.962315
4,Syflora Academy,Primary school only,False,True,True,4.0,8.0,66.0,10.0,True,4.0,29.0,37.0,2.0,6.0,25/04/2014,formal_only,EZJOH,Mpape,Dutse,private,education,1396959110576.jpg,9.141155 7.499665000000001 693.2 4.7,e17acb1e-364a-4a90-9384-0d612bb240c5,fct_bwari,9.141155,7.499665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98662,Liberty Primary School,Pre-primary and Primary school combined,True,True,True,10.0,11.0,449.0,9.0,False,6.0,199.0,250.0,3.0,8.0,09/04/2014,formal_only,EMWBJ,Atan,Atan,private,education,1396871679634.jpg,6.66737138 3.09158342 74.0 5.0,010545d1-8fed-41fe-bcae-c142046a04e3,ogun_ado_odo_ota,6.667371,3.091583
98663,Anfani Primary School,Primary school only,True,True,False,8.0,9.0,253.0,8.0,False,6.0,188.0,65.0,9.0,0.0,13/04/2014,formal_only,EIEMQ,Anfani,Nasarawa,public,education,1396966652017.jpg,9.924088236017527 4.634761001792765 192.104372...,5d81b15f-a114-4987-adce-70b67744f3ad,niger_magama,9.924088,4.634761
98664,OLUMAWU BASIC SCHOOL,Pre-primary and Primary school combined,True,True,True,77.0,77.0,567.0,40.0,True,48.0,296.0,271.0,40.0,37.0,02/05/2014,formal_only,EAFKM,WUSE 2,WUSE II,private,education,1398257399697.jpg,9.071785 7.477803333333332 474.9 5.0,6d63ceb8-bca5-4702-8313-41944e2d2dbd,fct_municipal_area_council,9.071785,7.477803
98665,UBE Akudu Karreh,Pre-primary and Primary school combined,False,False,False,3.0,10.0,330.0,6.0,False,0.0,180.0,150.0,5.0,5.0,21/05/2014,formal_only,EZLFV,Akudu Akarreh,Karreh,public,education,1394973132370.jpg,10.77455242 8.36796434 744.0 81.0,e22ff822-bf51-4a22-81b8-32ba8642b0f7,kaduna_kubau,10.774552,8.367964
98666,Government Pry School Efut Ibonda,Pre-primary and Primary school combined,False,False,False,7.0,13.0,618.0,6.0,False,0.0,332.0,286.0,9.0,4.0,17/04/2014,formal_only,EJMDC,Efut Ibonda Community,Adiabo Efut Ward,public,education,1397642929962.jpg,5.03017455 8.2667556 66.80000305175781 5.0,68027644-9dad-4c04-b458-95fcd7de1981,cross_river_odukpani,5.030175,8.266756

In [3]:
df.columns

Index(['facility_name', 'facility_type_display', 'improved_water_supply',
       'improved_sanitation', 'chalkboard_each_classroom_yn',
       'num_tchrs_with_nce', 'num_tchr_full_time', 'num_students_total',
       'num_classrms_total', 'phcn_electricity', 'num_toilets_total',
       'num_students_male', 'num_students_female', 'num_tchrs_male',
       'num_tchrs_female', 'date_of_survey', 'education_type', 'facility_id',
       'community', 'ward', 'management', 'sector', 'formhub_photo_id', 'gps',
       'survey_id', 'unique_lga', 'latitude', 'longitude'],
      dtype='str')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 98667 entries, 0 to 98666
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   facility_name                 98452 non-null  str
 1   facility_type_display         97764 non-null  str
 2   improved_water_supply         98388 non-null  object
 3   improved_sanitation           98370 non-null  object
 4   chalkboard_each_classroom_yn  96506 non-null  object
 5   num_tchrs_with_nce            95137 non-null  float64
 6   num_tchr_full_time            96503 non-null  float64
 7   num_students_total            93405 non-null  float64
 8   num_classrms_total            95375 non-null  float64
 9   phcn_electricity              98390 non-null  object
 10  num_toilets_total             95705 non-null  float64
 11  num_students_male             94292 non-null  float64
 12  num_students_female           94321 non-null  float64
 13  num_tchrs_male                94987 non-null  float64
 14  num_tchrs_female              95348 non-null  float64
 15  date_of_survey                98667 non-null  str
 16  education_type                98446 non-null  str
 17  facility_id                   98667 non-null  str
 18  community                     98429 non-null  str
 19  ward                          97896 non-null  str
 20  management                    97444 non-null  str
 21  sector                        98667 non-null  str
 22  formhub_photo_id              98667 non-null  str
 23  gps                           98667 non-null  str
 24  survey_id                     98667 non-null  str
 25  unique_lga                    98666 non-null  str
 26  latitude                      98667 non-null  float64
 27  longitude                     98667 non-null  float64
dtypes: float64(11), object(4), str(13)
memory usage: 21.1+ MB

In [5]:
df.isna().sum()

facility_name                    215
facility_type_display            903
improved_water_supply            279
improved_sanitation              297
chalkboard_each_classroom_yn    2161
num_tchrs_with_nce              3530
num_tchr_full_time              2164
num_students_total              5262
num_classrms_total              3292
phcn_electricity                 277
num_toilets_total               2962
num_students_male               4375
num_students_female             4346
num_tchrs_male                  3680
num_tchrs_female                3319
date_of_survey                     0
education_type                   221
facility_id                        0
community                        238
ward                             771
management                      1223
sector                             0
formhub_photo_id                   0
gps                                0
survey_id                          0
unique_lga                         1
latitude                           0
longitude                          0
dtype: int64

In [6]:
 df.describe()

,num_tchrs_with_nce,num_tchr_full_time,num_students_total,num_classrms_total,num_toilets_total,num_students_male,num_students_female,num_tchrs_male,num_tchrs_female,latitude,longitude
count,95137.000000,96503.000000,93405.000000,95375.000000,95705.000000,94292.000000,94321.000000,94987.000000,95348.000000,98667.000000,98667.000000
mean,7.017922,11.666197,335.406306,8.443512,2.546722,187.804628,169.837438,5.723583,5.957985,8.636626,7.183757
std,8.045479,14.033793,343.354223,7.110507,5.768857,257.891030,227.880995,6.205914,8.519480,2.403356,2.353375
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.280918,2.707594
25%,2.000000,4.000000,118.000000,4.000000,0.000000,59.000000,50.000000,2.000000,0.000000,6.671873,5.327685
50%,5.000000,8.000000,223.000000,6.000000,0.000000,114.000000,100.000000,4.000000,3.000000,8.140478,7.303945
75%,9.000000,14.000000,419.000000,11.000000,4.000000,220.000000,200.000000,7.000000,8.000000,10.631606,8.566094
max,100.000000,899.000000,2355.000000,514.000000,418.000000,7677.000000,6689.000000,100.000000,100.000000,13.875585,14.636391

In [7]:
df.drop(columns = {
    'formhub_photo_id',
    'gps',
    'survey_id',
    'facility_id'
}, inplace=True)
df.head()

,facility_name,facility_type_display,improved_water_supply,improved_sanitation,chalkboard_each_classroom_yn,num_tchrs_with_nce,num_tchr_full_time,num_students_total,num_classrms_total,phcn_electricity,num_toilets_total,num_students_male,num_students_female,num_tchrs_male,num_tchrs_female,date_of_survey,education_type,community,ward,management,sector,unique_lga,latitude,longitude
0,CPS SWALI,Primary school only,True,True,False,9.0,9.0,776.0,12.0,False,21.0,383.0,393.0,5.0,4.0,04/03/2014,formal_only,Swali,3,public,education,bayelsa_yenagoa,4.916910,6.274128
1,NANA Basic Academy,Primary and Junior Secondary school combined,False,False,NaN,NaN,NaN,NaN,NaN,False,0.0,NaN,NaN,NaN,NaN,02/05/2014,formal_only,Mpape,Dutse,private,education,fct_bwari,9.140918,7.496762
2,L.E.A Primary School Pabeyi,Primary school only,True,True,False,9.0,11.0,283.0,9.0,False,2.0,185.0,98.0,9.0,2.0,02/05/2014,formal_only,Pabeyi,Dobi,public,education,fct_gwagwalada,9.174855,7.022062
3,L.E.A.PrimarySchoolPagadna,Primary school only,False,True,False,4.0,5.0,247.0,7.0,False,2.0,147.0,100.0,5.0,0.0,25/04/2014,formal_only,Pagadna,Dobi,public,education,fct_gwagwalada,9.115847,6.962315
4,Syflora Academy,Primary school only,False,True,True,4.0,8.0,66.0,10.0,True,4.0,29.0,37.0,2.0,6.0,25/04/2014,formal_only,Mpape,Dutse,private,education,fct_bwari,9.141155,7.499665

In [8]:
df.rename(columns={
    'facility_name': 'School_name',
    'facility_type_display': 'School_type',
    'improved_water_supply': 'Improved_water_supply',
    'improved_sanitation': 'Improved_sanitation',
    'chalkboard_each_classroom_yn': 'Chalkboard_in_classroom',
    'num_tchrs_with_nce': 'Nce_qualified_teachers',
    'num_tchr_full_time': 'Full_time_teachers',
    'num_students_total': 'Total_students',
    'num_classrms_total': 'Total_classrooms',
    'phcn_electricity': 'Electricity_access',
    'num_toilets_total': 'Total_toilets',
    'num_students_male': 'Male_students',
    'num_students_female': 'Female_students',
    'num_tchrs_male': 'Male_teachers',	
    'num_tchrs_female':	'Female_teachers',
    'date_of_survey': 'Survey_date',
    'education_type': 'Education_type',	
    'community': 'Community',	
    'ward': 'Ward',	
    'management': 'Management_type',	
    'sector': 'Sector',	
    'unique_lga': 'Unique_lga',	
    'latitude': 'Latitude',	
    'longitude': 'Longitude'
    
}, inplace=True)
df.head()

,School_name,School_type,Improved_water_supply,Improved_sanitation,Chalkboard_in_classroom,Nce_qualified_teachers,Full_time_teachers,Total_students,Total_classrooms,Electricity_access,Total_toilets,Male_students,Female_students,Male_teachers,Female_teachers,Survey_date,Education_type,Community,Ward,Management_type,Sector,Unique_lga,Latitude,Longitude
0,CPS SWALI,Primary school only,True,True,False,9.0,9.0,776.0,12.0,False,21.0,383.0,393.0,5.0,4.0,04/03/2014,formal_only,Swali,3,public,education,bayelsa_yenagoa,4.916910,6.274128
1,NANA Basic Academy,Primary and Junior Secondary school combined,False,False,NaN,NaN,NaN,NaN,NaN,False,0.0,NaN,NaN,NaN,NaN,02/05/2014,formal_only,Mpape,Dutse,private,education,fct_bwari,9.140918,7.496762
2,L.E.A Primary School Pabeyi,Primary school only,True,True,False,9.0,11.0,283.0,9.0,False,2.0,185.0,98.0,9.0,2.0,02/05/2014,formal_only,Pabeyi,Dobi,public,education,fct_gwagwalada,9.174855,7.022062
3,L.E.A.PrimarySchoolPagadna,Primary school only,False,True,False,4.0,5.0,247.0,7.0,False,2.0,147.0,100.0,5.0,0.0,25/04/2014,formal_only,Pagadna,Dobi,public,education,fct_gwagwalada,9.115847,6.962315
4,Syflora Academy,Primary school only,False,True,True,4.0,8.0,66.0,10.0,True,4.0,29.0,37.0,2.0,6.0,25/04/2014,formal_only,Mpape,Dutse,private,education,fct_bwari,9.141155,7.499665

In [9]:
df.dropna(subset=['School_name'], inplace=True)
df['School_name'].isna().sum()

np.int64(0)

In [10]:
df.dropna(subset=['Unique_lga'], inplace=True)
df['Unique_lga'].isna().sum()

np.int64(0)

In [11]:
df.isna().sum()

School_name                   0
School_type                 764
Improved_water_supply       139
Improved_sanitation         157
Chalkboard_in_classroom    2009
Nce_qualified_teachers     3375
Full_time_teachers         2162
Total_students             5079
Total_classrooms           3119
Electricity_access          137
Total_toilets              2814
Male_students              4214
Female_students            4185
Male_teachers              3517
Female_teachers            3156
Survey_date                   0
Education_type               81
Community                    91
Ward                        625
Management_type            1075
Sector                        0
Unique_lga                    0
Latitude                      0
Longitude                     0
dtype: int64

In [12]:
bool_cols = ['Improved_water_supply', 'Improved_sanitation', 'Chalkboard_in_classroom', 'Electricity_access']
for col in bool_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

In [13]:
df.head()

,School_name,School_type,Improved_water_supply,Improved_sanitation,Chalkboard_in_classroom,Nce_qualified_teachers,Full_time_teachers,Total_students,Total_classrooms,Electricity_access,Total_toilets,Male_students,Female_students,Male_teachers,Female_teachers,Survey_date,Education_type,Community,Ward,Management_type,Sector,Unique_lga,Latitude,Longitude
0,CPS SWALI,Primary school only,true,true,false,9.0,9.0,776.0,12.0,false,21.0,383.0,393.0,5.0,4.0,04/03/2014,formal_only,Swali,3,public,education,bayelsa_yenagoa,4.916910,6.274128
1,NANA Basic Academy,Primary and Junior Secondary school combined,false,false,NaN,NaN,NaN,NaN,NaN,false,0.0,NaN,NaN,NaN,NaN,02/05/2014,formal_only,Mpape,Dutse,private,education,fct_bwari,9.140918,7.496762
2,L.E.A Primary School Pabeyi,Primary school only,true,true,false,9.0,11.0,283.0,9.0,false,2.0,185.0,98.0,9.0,2.0,02/05/2014,formal_only,Pabeyi,Dobi,public,education,fct_gwagwalada,9.174855,7.022062
3,L.E.A.PrimarySchoolPagadna,Primary school only,false,true,false,4.0,5.0,247.0,7.0,false,2.0,147.0,100.0,5.0,0.0,25/04/2014,formal_only,Pagadna,Dobi,public,education,fct_gwagwalada,9.115847,6.962315
4,Syflora Academy,Primary school only,false,true,true,4.0,8.0,66.0,10.0,true,4.0,29.0,37.0,2.0,6.0,25/04/2014,formal_only,Mpape,Dutse,private,education,fct_bwari,9.141155,7.499665

In [14]:
for col in bool_cols:
    df[col] = df[col].fillna(df[col].mode())
df[bool_cols].dtypes

Improved_water_supply      str
Improved_sanitation        str
Chalkboard_in_classroom    str
Electricity_access         str
dtype: object

In [15]:
bool_cols = ['Improved_water_supply', 'Improved_sanitation', 'Chalkboard_in_classroom', 'Electricity_access']
for col in bool_cols:
    df[col] = df[col].map({'true': True, 'false': False})
    df[col] = df[col].astype(bool)

In [16]:
df[bool_cols].dtypes

Improved_water_supply      bool
Improved_sanitation        bool
Chalkboard_in_classroom    bool
Electricity_access         bool
dtype: object

In [17]:
df.head()

,School_name,School_type,Improved_water_supply,Improved_sanitation,Chalkboard_in_classroom,Nce_qualified_teachers,Full_time_teachers,Total_students,Total_classrooms,Electricity_access,Total_toilets,Male_students,Female_students,Male_teachers,Female_teachers,Survey_date,Education_type,Community,Ward,Management_type,Sector,Unique_lga,Latitude,Longitude
0,CPS SWALI,Primary school only,True,True,False,9.0,9.0,776.0,12.0,False,21.0,383.0,393.0,5.0,4.0,04/03/2014,formal_only,Swali,3,public,education,bayelsa_yenagoa,4.916910,6.274128
1,NANA Basic Academy,Primary and Junior Secondary school combined,False,False,True,NaN,NaN,NaN,NaN,False,0.0,NaN,NaN,NaN,NaN,02/05/2014,formal_only,Mpape,Dutse,private,education,fct_bwari,9.140918,7.496762
2,L.E.A Primary School Pabeyi,Primary school only,True,True,False,9.0,11.0,283.0,9.0,False,2.0,185.0,98.0,9.0,2.0,02/05/2014,formal_only,Pabeyi,Dobi,public,education,fct_gwagwalada,9.174855,7.022062
3,L.E.A.PrimarySchoolPagadna,Primary school only,False,True,False,4.0,5.0,247.0,7.0,False,2.0,147.0,100.0,5.0,0.0,25/04/2014,formal_only,Pagadna,Dobi,public,education,fct_gwagwalada,9.115847,6.962315
4,Syflora Academy,Primary school only,False,True,True,4.0,8.0,66.0,10.0,True,4.0,29.0,37.0,2.0,6.0,25/04/2014,formal_only,Mpape,Dutse,private,education,fct_bwari,9.141155,7.499665

In [18]:
catg_cols = ['School_type', 'Education_type', 'Community', 'Ward', 'Management_type']
for col in catg_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [19]:
num_cols = ['Nce_qualified_teachers', 'Full_time_teachers', 'Total_students', 'Total_classrooms', 'Total_toilets', 'Male_students',
            'Female_students', 'Male_teachers', 'Female_teachers']
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [20]:
df.isna().sum()

School_name                0
School_type                0
Improved_water_supply      0
Improved_sanitation        0
Chalkboard_in_classroom    0
Nce_qualified_teachers     0
Full_time_teachers         0
Total_students             0
Total_classrooms           0
Electricity_access         0
Total_toilets              0
Male_students              0
Female_students            0
Male_teachers              0
Female_teachers            0
Survey_date                0
Education_type             0
Community                  0
Ward                       0
Management_type            0
Sector                     0
Unique_lga                 0
Latitude                   0
Longitude                  0
dtype: int64

In [21]:
df.head()

,School_name,School_type,Improved_water_supply,Improved_sanitation,Chalkboard_in_classroom,Nce_qualified_teachers,Full_time_teachers,Total_students,Total_classrooms,Electricity_access,Total_toilets,Male_students,Female_students,Male_teachers,Female_teachers,Survey_date,Education_type,Community,Ward,Management_type,Sector,Unique_lga,Latitude,Longitude
0,CPS SWALI,Primary school only,True,True,False,9.0,9.0,776.0,12.0,False,21.0,383.0,393.0,5.0,4.0,04/03/2014,formal_only,Swali,3,public,education,bayelsa_yenagoa,4.916910,6.274128
1,NANA Basic Academy,Primary and Junior Secondary school combined,False,False,True,5.0,8.0,223.0,6.0,False,0.0,114.0,100.0,4.0,3.0,02/05/2014,formal_only,Mpape,Dutse,private,education,fct_bwari,9.140918,7.496762
2,L.E.A Primary School Pabeyi,Primary school only,True,True,False,9.0,11.0,283.0,9.0,False,2.0,185.0,98.0,9.0,2.0,02/05/2014,formal_only,Pabeyi,Dobi,public,education,fct_gwagwalada,9.174855,7.022062
3,L.E.A.PrimarySchoolPagadna,Primary school only,False,True,False,4.0,5.0,247.0,7.0,False,2.0,147.0,100.0,5.0,0.0,25/04/2014,formal_only,Pagadna,Dobi,public,education,fct_gwagwalada,9.115847,6.962315
4,Syflora Academy,Primary school only,False,True,True,4.0,8.0,66.0,10.0,True,4.0,29.0,37.0,2.0,6.0,25/04/2014,formal_only,Mpape,Dutse,private,education,fct_bwari,9.141155,7.499665

In [22]:
from dateutil import parser
def date_parser(date_str):
    try:
        return parser.parse(date_str, dayfirst=True)
    except Exception:
        return pd.NaT
df['Survey_date'] = df['Survey_date'].apply(date_parser)

df['Survey_date']

0       2014-03-04
1       2014-05-02
2       2014-05-02
3       2014-04-25
4       2014-04-25
           ...
98662   2014-04-09
98663   2014-04-13
98664   2014-05-02
98665   2014-05-21
98666   2014-04-17
Name: Survey_date, Length: 98451, dtype: datetime64[us]

In [23]:
df['School_type'] = df['School_type'].astype(str).str.strip().str.lower()

In [24]:
df['School_type'].value_counts()

School_type
primary only                                            29025
pre-primary and primary                                 18837
primary school only                                     15153
pre-primary and primary school combined                 10840
junior secondary only                                    5276
junior and senior secondary                              5215
junior and senior secondary school combined              4122
junior secondary school only                             1922
pre-primary only                                         1898
senior secondary only                                    1476
primary, junior, and senior secondary                     968
primary and junior secondary                              944
primary and junior secondary school combined              912
information not available / don't know                    797
primary, junior and senior secondary school combined      763
adult, vocational, or technical                           303
Name: count, dtype: int64

In [25]:
df['School_type'] = df['School_type'].replace({
    'primary only': 'primary school only',
    'pre-primary and primary': 'pre-primary and primary school combined',
    'junior secondary only': 'junior secondary school only',
    'junior and senior secondary': 'junior and senior secondary school combined',
    'primary, junior, and senior secondary': 'primary, junior and senior secondary school combined',
    'primary and junior secondary': 'primary and junior secondary school combined'
})
df['School_type'].value_counts()

School_type
primary school only                                     44178
pre-primary and primary school combined                 29677
junior and senior secondary school combined              9337
junior secondary school only                             7198
pre-primary only                                         1898
primary and junior secondary school combined             1856
primary, junior and senior secondary school combined     1731
senior secondary only                                    1476
information not available / don't know                    797
adult, vocational, or technical                           303
Name: count, dtype: int64

In [26]:
df = df[df['School_type'] != "information not available / don't know"]
df['School_type'].value_counts()

School_type
primary school only                                     44178
pre-primary and primary school combined                 29677
junior and senior secondary school combined              9337
junior secondary school only                             7198
pre-primary only                                         1898
primary and junior secondary school combined             1856
primary, junior and senior secondary school combined     1731
senior secondary only                                    1476
adult, vocational, or technical                           303
Name: count, dtype: int64

In [27]:
df['Education_type'].value_counts()

Education_type
Formal Only       58598
formal_only       32002
Integrated         3998
integrated         1650
religious_only      716
Religious Only      651
dk                   39
Name: count, dtype: int64

In [28]:
df['Education_type'] = df['Education_type'].astype(str).str.strip().str.lower()
df['Education_type'].value_counts()

Education_type
formal only       58598
formal_only       32002
integrated         5648
religious_only      716
religious only      651
dk                   39
Name: count, dtype: int64

In [29]:
df['Education_type'] = df['Education_type'].replace({
    'formal only': 'formal_only',
    'religious only': 'religious_only'
})

In [30]:
df['Education_type'] = df['Education_type']. replace('dk', df['Education_type'].mode()[0])
df['Education_type'].value_counts()

Education_type
formal_only       90639
integrated         5648
religious_only     1367
Name: count, dtype: int64

In [31]:
df['Management_type'].value_counts()

Management_type
public         75620
private        20566
faith_based     1451
none              17
Name: count, dtype: int64

In [32]:
df = df[df['Management_type'].str.strip().str.lower() != "none"]
df['Management_type'].value_counts()

Management_type
public         75620
private        20566
faith_based     1451
Name: count, dtype: int64

In [33]:
df['Unique_lga'] = df['Unique_lga'].astype(str).str.strip().str.lower()
df['Unique_lga'].value_counts()

Unique_lga
ogun_ifo               565
kaduna_chikun          432
kaduna_kachia          331
benue_buruku           328
delta_uvwie            328
                      ...
borno_marte             14
yobe_yusufari           12
cross_river_bakassi     10
borno_ngala              6
borno_kwaya_kusar        3
Name: count, Length: 772, dtype: int64

In [34]:
df.dtypes

School_name                           str
School_type                           str
Improved_water_supply                bool
Improved_sanitation                  bool
Chalkboard_in_classroom              bool
Nce_qualified_teachers            float64
Full_time_teachers                float64
Total_students                    float64
Total_classrooms                  float64
Electricity_access                   bool
Total_toilets                     float64
Male_students                     float64
Female_students                   float64
Male_teachers                     float64
Female_teachers                   float64
Survey_date                datetime64[us]
Education_type                        str
Community                             str
Ward                                  str
Management_type                       str
Sector                                str
Unique_lga                            str
Latitude                          float64
Longitude                         float64
dtype: object

In [35]:
df['Total_teachers'] = df['Male_teachers'] + df['Female_teachers']
df.head()

,School_name,School_type,Improved_water_supply,Improved_sanitation,Chalkboard_in_classroom,Nce_qualified_teachers,Full_time_teachers,Total_students,Total_classrooms,Electricity_access,Total_toilets,Male_students,Female_students,Male_teachers,Female_teachers,Survey_date,Education_type,Community,Ward,Management_type,Sector,Unique_lga,Latitude,Longitude,Total_teachers
0,CPS SWALI,primary school only,True,True,False,9.0,9.0,776.0,12.0,False,21.0,383.0,393.0,5.0,4.0,2014-03-04,formal_only,Swali,3,public,education,bayelsa_yenagoa,4.916910,6.274128,9.0
1,NANA Basic Academy,primary and junior secondary school combined,False,False,True,5.0,8.0,223.0,6.0,False,0.0,114.0,100.0,4.0,3.0,2014-05-02,formal_only,Mpape,Dutse,private,education,fct_bwari,9.140918,7.496762,7.0
2,L.E.A Primary School Pabeyi,primary school only,True,True,False,9.0,11.0,283.0,9.0,False,2.0,185.0,98.0,9.0,2.0,2014-05-02,formal_only,Pabeyi,Dobi,public,education,fct_gwagwalada,9.174855,7.022062,11.0
3,L.E.A.PrimarySchoolPagadna,primary school only,False,True,False,4.0,5.0,247.0,7.0,False,2.0,147.0,100.0,5.0,0.0,2014-04-25,formal_only,Pagadna,Dobi,public,education,fct_gwagwalada,9.115847,6.962315,5.0
4,Syflora Academy,primary school only,False,True,True,4.0,8.0,66.0,10.0,True,4.0,29.0,37.0,2.0,6.0,2014-04-25,formal_only,Mpape,Dutse,private,education,fct_bwari,9.141155,7.499665,8.0

In [36]:
df['Expected_total'] = df['Male_students'] + df['Female_students']

In [37]:
(df['Expected_total'] != df['Total_students']).sum()

np.int64(5377)

In [38]:
df['Total_students'] = df['Male_students'] + df['Female_students']
df.head()

,School_name,School_type,Improved_water_supply,Improved_sanitation,Chalkboard_in_classroom,Nce_qualified_teachers,Full_time_teachers,Total_students,Total_classrooms,Electricity_access,Total_toilets,Male_students,Female_students,Male_teachers,Female_teachers,Survey_date,Education_type,Community,Ward,Management_type,Sector,Unique_lga,Latitude,Longitude,Total_teachers,Expected_total
0,CPS SWALI,primary school only,True,True,False,9.0,9.0,776.0,12.0,False,21.0,383.0,393.0,5.0,4.0,2014-03-04,formal_only,Swali,3,public,education,bayelsa_yenagoa,4.916910,6.274128,9.0,776.0
1,NANA Basic Academy,primary and junior secondary school combined,False,False,True,5.0,8.0,214.0,6.0,False,0.0,114.0,100.0,4.0,3.0,2014-05-02,formal_only,Mpape,Dutse,private,education,fct_bwari,9.140918,7.496762,7.0,214.0
2,L.E.A Primary School Pabeyi,primary school only,True,True,False,9.0,11.0,283.0,9.0,False,2.0,185.0,98.0,9.0,2.0,2014-05-02,formal_only,Pabeyi,Dobi,public,education,fct_gwagwalada,9.174855,7.022062,11.0,283.0
3,L.E.A.PrimarySchoolPagadna,primary school only,False,True,False,4.0,5.0,247.0,7.0,False,2.0,147.0,100.0,5.0,0.0,2014-04-25,formal_only,Pagadna,Dobi,public,education,fct_gwagwalada,9.115847,6.962315,5.0,247.0
4,Syflora Academy,primary school only,False,True,True,4.0,8.0,66.0,10.0,True,4.0,29.0,37.0,2.0,6.0,2014-04-25,formal_only,Mpape,Dutse,private,education,fct_bwari,9.141155,7.499665,8.0,66.0

In [39]:
(df['Expected_total'] != df['Total_students']).sum()

np.int64(0)

In [40]:
student_ratio = df['Total_students'] / df['Total_teachers']
df['Student_to_teacher_ratio'] = round(student_ratio, 0)
df.head()

,School_name,School_type,Improved_water_supply,Improved_sanitation,Chalkboard_in_classroom,Nce_qualified_teachers,Full_time_teachers,Total_students,Total_classrooms,Electricity_access,Total_toilets,Male_students,Female_students,Male_teachers,Female_teachers,Survey_date,Education_type,Community,Ward,Management_type,Sector,Unique_lga,Latitude,Longitude,Total_teachers,Expected_total,Student_to_teacher_ratio
0,CPS SWALI,primary school only,True,True,False,9.0,9.0,776.0,12.0,False,21.0,383.0,393.0,5.0,4.0,2014-03-04,formal_only,Swali,3,public,education,bayelsa_yenagoa,4.916910,6.274128,9.0,776.0,86.0
1,NANA Basic Academy,primary and junior secondary school combined,False,False,True,5.0,8.0,214.0,6.0,False,0.0,114.0,100.0,4.0,3.0,2014-05-02,formal_only,Mpape,Dutse,private,education,fct_bwari,9.140918,7.496762,7.0,214.0,31.0
2,L.E.A Primary School Pabeyi,primary school only,True,True,False,9.0,11.0,283.0,9.0,False,2.0,185.0,98.0,9.0,2.0,2014-05-02,formal_only,Pabeyi,Dobi,public,education,fct_gwagwalada,9.174855,7.022062,11.0,283.0,26.0
3,L.E.A.PrimarySchoolPagadna,primary school only,False,True,False,4.0,5.0,247.0,7.0,False,2.0,147.0,100.0,5.0,0.0,2014-04-25,formal_only,Pagadna,Dobi,public,education,fct_gwagwalada,9.115847,6.962315,5.0,247.0,49.0
4,Syflora Academy,primary school only,False,True,True,4.0,8.0,66.0,10.0,True,4.0,29.0,37.0,2.0,6.0,2014-04-25,formal_only,Mpape,Dutse,private,education,fct_bwari,9.141155,7.499665,8.0,66.0,8.0

In [43]:
ward = df['Ward'].unique().tolist()
print(ward)

['3', 'Dutse', 'Dobi', 'Paiko', 'Kutunku', 'Byazhin', 'Dutse Alhaji', 'Kubwa', '4', 'Akpet abini', 'Ehom', 'UTUGWANG CENTRAL', 'UTUGWANG NORTH', 'Okere', '14', '12', '1', '5', 'Lazuru', '8', '9', 'Silame', 'DALLAJE', 'TAMA', 'Arak', 'Serti Ã¢Â€Â˜AÃ¢Â€Â˜', 'Garbabi', 'ZAMBUK KWALI', 'Tungo', 'Sade', 'Gabarin', 'Darazo West', 'Darazo west', 'Darazo East', 'Mbal', 'Michika 2', 'ALEGE UBANG', '7', 'Nsu B', 'Aba River', 'Erunkun', 'ODE WARD 3', 'Aisegba ward 1', 'Dokan Kasuwa East', 'Kwang', 'Turu', 'Aso Kodape', 'Bununu', '11', 'Ibwa', 'Ward 5 umunkwo', 'Ward 5 uda layout phase 1', 'Ward 7 umuagu quarters', 'Ward 9 dla road', 'IBWA', 'Umuoke', 'Ulakwo', 'Igbodo', 'Ward12', 'New owerri', 'Ward 3', 'Ward 10', 'Umuechi', 'Choba 15', 'Eliogbolo 7', '6', '13', '20', 'Chugwi', 'Kuru B', 'Zawan B', '2', 'Umuororonjo', 'Luukwo', 'Du', 'Giring', 'Mbakura', 'Mbaakura', 'Mbaya', 'Mbaapen', 'Mbakyaan', 'Bokkos', 'Butura', 'Mbatyough', 'Etulo', 'Mbakyan', 'Agbalu', 'Egwi', 'Okomoko (ward 5)', 'Akwuobuo', 'Mbapen', 'Rafinkada', 'Avyi', 'GRA', 'Jibu', 'Amassoma Ward 10', 'Oporoma 2', 'Ward 2', 'Du A', 'Zawan A', 'Bukuru', 'Amassoma 10', 'Amassoma Ward10', 'Oporoma ward 2', 'Igeibiri Ward 2', 'Igeibiri ward 2', 'Oporoma Ward 2', 'Gyel A', 'Amassoma Ward 9', 'Kwande', 'Gyel B', 'Kurgwi East', 'Kwoor', 'Doemak Koplong', 'Balbaya', 'DORO', 'Kurgwi West', 'Puje', 'Nassarafu', 'Bariki', 'Lusa A', 'Tsukundi', 'Bantaje', 'GIREMAWA', 'Mushere north', 'Mushere west', 'Kopmur', 'Kopmur/margif', 'BAURE', 'Sha', 'Ward 9', 'SHIBDAWA', 'Masaga  A', 'JIBAWA', 'DALLAJI', 'Chonku', 'TAMA ', 'GAIWA', 'BINDAWA', 'Manguna', 'KAMRI', 'Maguna', 'Mangor', 'Mbakuha', 'Mbaawe', 'Mayo Ranewo', 'Sarki Dutse', 'Lamido Borno', 'Barkin Dutse', 'Jauro Nyinnu', 'Sunkani', '10', 'Mbaaka', 'Ward IV', 'Ward II', 'Ward III', 'Ward 1', 'Ward I', 'Adupi etteh', 'Ifako', 'Burum burum iggah', 'Ojota', 'Maryland ', 'Oworonsoki', 'Boi B', 'Bogoro D', 'Dutsen Lawan', 'Ibesikpo 1', 'Ward 5', '18', 'Gwange', 'Maisandari', 'Ihitte Nsu', 'Maryland', 'Bare', 'Kodomti', 'Ward2', 'Ward1', 'Imburu', 'Sabon pegi', 'Rumuolumeni', 'ZAGGA/KWASARA', 'BAGUDO/TUGA', 'Eda Obada 2', 'Ikov', 'Mbagwaza', 'Ogberuru/Obibi', 'Mbayegh', 'Ogudu', 'Eda Oniyo', 'Iludun', 'Umuna', 'Mbagba', 'Amasiri ward c', 'Iye 1', 'Amasiri Ward B', 'Iye 2', 'Ogba ubbe gaji', 'Tsukumu tillijo', 'Madzi', 'BANI/TSAMIYA', 'Lolo/Giris', 'Zagga/kwasara', 'Bagudo/tuga', 'Ayeroju', 'Agbamere Umabor', 'Akambi 5', 'Akambi III', 'Atirkyese', 'Mbaagir', 'Agbamere-Umabor', 'Tsaragi Ward 2', 'Lafiagi ward 3', 'Tsaragi ward 1', 'Tsaragi ward 2', 'Shonga Ward 1', 'Wuyo', 'Fikayel', 'Teli', 'Ikenegbu ward 1', 'B/kudu', 'Oloba 6', 'Kiyako', 'Monguno', 'Mintar', 'Mandala', 'Kaguram', 'Wulo', 'Ward 6', 'Kantoga', 'Sure', 'Zulum', 'Surku', 'Lafiya', 'Surko', 'Ijagbo', 'Dogo Nini', 'Ilemona', 'Yerimaram', 'Ward 4', 'Ilaro I', 'Ilaro III', 'Kumalia', 'Gwarzo', 'Ogunu', 'Ode-Itsekiri', 'Igbudu 9', 'Igbudu 10', 'Kara', 'Lakwaya', 'Shonga Ward 3', 'Lafiagi Ward 4', 'Ohuhu', 'Ikotun', 'Ojoku', 'Ifo-2', 'Karu', 'Ipee', 'Nkpunato', 'Erinile North', 'Abakpa', 'Iji Nike Abakpa', 'Umuenwene', 'Umuchigbo Iji Nike', 'Ward 17 Ugbene 1', 'Gurku Kabusu', 'Manta', 'Ugbene Ward 17', 'Otukpo Township II', 'Gussoro zumba', 'Ugboju Otahe', 'G2', 'Ugboju Ehaje', 'Adoka Icho', 'E', 'Sarkin noma', 'Newlayout', 'Ede-Ukwu', 'Angwan Kura', 'A', 'Ward A', 'Ihe / Owere', 'Ihe/Owere', 'Shonga ward 2', 'Ward 8', 'Aisegba Ward 2', 'Isale Aro Ward 4', 'IJan Ward', 'Ajilosun', 'World Bank', 'Mobil', 'Kutama', 'Aso kodape', 'Nnebisi road, ward9', 'Basiri', 'Idemo Ado Ekiti', 'River Side', 'Idemo Sdo Ekiti', 'Dbs road asaba', 'Oke-ila', 'Igosun', 'Getso', 'Ekeoha', 'Federal Housing estate', 'Housing ado', 'Housing estate', 'Unguwar Tudu', 'Sabo Taraa', 'Awkunanaw', 'Ugwuaji', 'Gesto', 'Gbodofon Ward 4', 'Gabake', 'Okposi 2', 'Ijan Ward', 'Kagara', 'Okposhi Ehuku 2', 'Kasuwar Daji', 'Ogo Oluwa Ward 4', 'Odi-Olowo Ward 4', 'Gidigbo 1', 'Garzo', 'Oke-Adan 3', 'Ameku', 'Iluomoba Ward.', 'Erinile', 'Erinile South', 'Agbado ward', 'Gidigbo 3', 'Isale-Oba 3', 'Molete 3', 'Daksiri', 'Hong', 'Daksiri ward', 'Thilbang', 'IJan Ward 1', 'Hildi', 'UBA', 'Mada', 'Adekile', 'Bichi', '9 / Oluyoro Area', 'Isale-Oba 4', 'Muntsira', 'Imesi Ward', 'Imesi Ward.', 'Danzabuwa', 'Agbado Ward', 'Government secondary school senior Ipee', 'URBAN II', 'Ward 8, oke Ofa', 'Abadau', 'Kandawa', 'Karare', 'Agaha Obong 1', 'Afaha Obong1', 'Urban 3', 'Abogunde', 'Afahaobong 1', 'Midim2', 'Urban2', 'Urban 2', 'Midim1', 'Kaltungo West', 'Midim 1', 'Ture', 'Urban3', 'Yautare', 'Osupa', 'Afaha Obong 1', 'Awak', 'Urban1', 'Kamo', 'Tungo ward', 'Kaltungu East', 'Mamudo', 'Tudunmurtala', 'Bassa/kukuki', 'Osimore', 'Iruekpen 6', 'Giginyu', 'Yarimaram', 'Kaltungo East', 'Bolewa B', 'Tudunwada', 'Umuakagu Nsu', 'Hotoro', 'Gawuna', 'Gwagwarwa', 'Kawaji', 'Dakata', 'Afaka', 'Mah', 'Masifa/Aguodo', 'Kargi', 'Ward 11,sobe', 'Ajagba ward 8', 'Faudan', 'Bununy A', 'Bununu A', 'Ekrerhavwen', 'BANGANJE SOUTH', 'TUDU KWAYA ', 'Kanya', 'TODI', 'BILLIRI NORTH', 'Manawa', 'Batsari', 'Wasagu', 'Darazo east', 'TAL', 'Konkiyel', 'KALMAI WARD', 'Tauya east', 'Lago', 'Alagarno', 'Yalwan Darazo', 'Jarmai', 'Yalmo Shindi', 'Gamawa ward', 'Gwanfi Kele', '16', 'Danko Maga', 'Watd 10', 'Bare Bari Bauya Lai lai', 'Wawa', 'Tudun Wada', 'Bussa', 'Ribah Machika', 'Bokana', 'Owevwe', 'Oghara Agbarha', 'Ogbovwan', 'Oteri', 'Ward 15', 'Tuntube tsehe', 'Ward 08', 'Tsafanade', 'Gajara', 'Ota', 'Aboro', 'Ward 14 Oba', 'Ward 04', 'Tuntube tsefe', 'Shiyar Kayaye', 'Shirya Galadima', 'Shiyar Galadima', 'Garbadu', 'Makera/ Take Tsaba', 'Morai', 'Shiyar galadima', 'Ruwan bore', 'Dange', 'Ward  10', 'Nkpunano', 'New Owerri', 'Arak ward', 'F2', 'Isale Ijebu Ward 4', 'Oke Baale Ward 14', 'Nandu', 'Oke Ayepe Ward 8', 'Fadeyi Estate', 'Oke-Ijetu Ward 6', 'Ugboju Icho', 'Eguare 4', 'Ogidi 1', 'TANGLANG', 'Yaba Wabu', 'Udubo', 'Ward 11', 'Udubo ward', 'Idi/Ogbozalla', 'Idi/Ogbozara', 'Karaworo', 'Ibeku', 'Dila', 'Fadisonka', 'Fadi sonka', 'Gidan makama', 'Garki', 'BANGANJE NORTH', 'Abanyom', 'Nde', 'BILLIRI SOUTH', 'Umuogudu Akpu 1', 'Abocho', 'Emewe', 'UKPE', 'Dekina', 'Karabonde', 'Evwreni', 'Otogor', 'Ughelli', 'Eruemukohwarien', 'Ikweghwu agbarho ', 'Ibii', 'Umueze I', 'Asa', 'Uwani', 'Ohaisu ward A', 'Sabon Gari', 'Galadima', 'Madawaki', 'Kurya', 'Galadima Dangaladima', 'Kungurki', 'Sarkin Mafara Sarkin Baura', 'Sakajiki', 'Nkpoghoro', 'Umuogudu oshia', 'Kalgo', 'Ohaisu Ward A', 'Ilaro 3', 'Kwamarawa', 'Saye', 'Ohaisu ward B', 'Ilaro II', 'Ifo-1', 'Ward G', 'Ibogun-11', 'Irawo', 'Ifo-3', 'Ward 01', 'Bajoga west', 'WARD 09', 'Onitsha north 8', 'Onitsha north11', 'Ilaro ward III', 'Umuogudu Akpu 2', 'Bagoja West', 'Anchau', 'Avbiosi 5', 'Oke new 3', 'Jillahi', 'G North', 'Jallahi', 'Damau', 'Tongo', 'Irele ward 1', 'Irele ward 5', 'Irele Ward 5', 'Irele Ward 1', 'Irele ward 2', 'Ishingbo 1', 'Igbeba', 'Irele ward 6', 'Talbort Road', 'Ideani1', 'Apebi Isale', 'Apebi', 'Aboru Ifesowapo', 'Tilde Bodor', 'Ribadu', 'Kuptu', 'Darki', 'Wulari', 'Maduganari', 'Lamisula/jabbamari', 'Lamisula/jabamari/maduganari', 'Agbaja', 'Anyigba', 'Sanusi', 'Odo-Olowu', 'Airways', 'Karshi', 'Entekpa', 'Adoka Ehaje', 'Ikom urban', 'Umon south', 'Odu 2', 'Ayu', 'Ganda kauye', 'Shuyar Galadima', 'Egume', 'Irele ward 3', 'Gital', 'Lokongoma', 'Sarkin Magara Sarkin baura', 'Zangon Daji', 'Sarkin Mafara sarkin Baura', 'Oworo', 'Phase 2', 'Ajasa Meiran', 'Agbelekale', 'Meran Ajasa', 'Agbado', 'Quaters ward', 'Central', 'Akute', 'Ninzo north', 'Ikom urban 1', 'Ofutop 2 ', 'ROfutop 2', 'Wudil', 'Raushi', 'Achika', 'Ward 7', 'Amuzukwu Urban 2', 'Urban 1', 'Mayana', 'Owere/Umuoyo', 'Hausawa', 'Ngbo 1', 'Achina 2', 'Ishingbo 2', 'Fentolu', 'Orishigun', 'Ward 09', 'Kaukau', 'Kau kau', 'Okposhi Eshi 1', 'Ankara', 'Oke Odan', 'Ajilete', 'Iwoye', 'Haskiya', 'Ward 1 ', 'GWANI SHINGA WADE', 'Odu 1', 'Kwarau', 'Molipa', 'F', 'Idimu', 'G', 'Bajoga east', 'Oguduokwor', 'Ward E', 'Owode 1', 'Amechi_umuegara', 'Umuogele Mbato', 'Ward B', 'Gamawa north', 'Tandawa', 'Yandoji', 'Waje', 'Erena', 'HINNA', 'Deba', 'Lgea gwantu b', 'Porogun Alapo', 'Rigachikun', 'Marafa East', 'Labani', 'Katami North', 'Gwako', 'Amaifeke/Ofeahia', 'G/sharirai', 'Igboukwu 1', 'Df', 'Nru', 'Kagbi', 'Kagbu', 'Moda/dlaka', 'Michika 1', 'Wadata', 'Jigalambu', 'Jara Dali', 'Jara Gol', 'Gamadadi', 'Amike', 'Umme', 'Wakama', 'Owerre-Ebeiri', 'Vulpi', 'Tauya', 'Yayari', 'Dagauda', 'Gargawa', 'Dewu', 'Jengre', 'Ali Kazuare', 'Targwong Rigizah', 'Lamingo', 'Mazah', 'Kunga', 'Alheri', 'Vwang', ' Du', 'Gyel', 'Akate', 'Kadarko', 'MAITAMA', 'WUSE', 'WUSE II', 'Wuse III', 'GADUWA', 'DURUMI', 'WUSEIII', 'JAGALI SOUTH', 'NONO', 'KURI LANO', 'KURI', 'LANO KWAJI', 'JAGALI NORTH', 'KANAWA', 'Kwadam liji', 'Uba', 'Asibiti', 'Ado', 'Oke Ila', 'Zambuk kushi', 'Wurnoyel primary school', 'Lubo difa', 'Ifelodun ward 10', 'Kwadon liji', 'Midm 1', 'Kwadon kurba', 'Gwadam liji', 'Lubo', 'Kawa wajari', 'Kanawa wajari', 'Kanawa wajari nono', 'Nono kunuwal', 'GWANI SHINGA', 'Kuru a', 'Du b', 'Kuno lano lambam', 'Kuri lano lambam', 'Jagali south', 'ASUBIARO WARD 03', 'AJOBO WARD 03', 'ODI-OLOWO WARD 04', 'OGO-OLUWA WARD 04', 'Luggere', 'Du a', 'Karewa', 'Nasarawo', 'Rabin du', 'Olugunna , ward 9', 'Du B', 'Desawo', 'Jambutu', 'Zawan', 'LIJI KWADON', 'Gye b', 'Zawan b', 'LUBO DIFA', 'Lyoh rak', 'Gwadabawa', 'Gyel a', 'Kuru A', 'Gut rayfield', 'Lubo Difa', 'Kwang du', 'AWOSURU,WARD 05', 'WAEC AREA,WARD 04', 'OFF ADEWUYI,ALEKUWODO WARD 04', 'BACK OF NECO OFFICE WARD 04', 'ANGIABA/BEGIAKA', 'Ward 14', 'Kuru b', 'Arolu', 'Zabolo', 'Asak', 'Kasuru', 'Rimi', 'Kimakpa', 'TaÃ¢Â€Â˜agbe', 'TaÃ¢Â€Â˜agwe', 'Ancha', 'Tahu', 'Kakkek', 'Marafa', 'Suwa ward', 'SUWA WARD', 'Waduku', 'Suwa', 'SUWA', 'WADUKU WARD', 'Ngbebongun', 'Dubwange', 'Gyawana', 'Lamurde', 'Rigange', 'Gurum A', 'Buji', 'Eight', 'Ngbakawo', 'Kishika', 'Buhit', 'Kimapa', 'Kwall', "Ta'agbe", 'Bital', 'Kwassam', 'Umudagu', 'IDON', 'AFOGO', 'KALLAH', 'BUDA', 'TANTATU', 'KASUWAN MAGANI', 'Zangon Aya', 'Igabi', 'Panshanu', 'WARD1', 'WARD5', 'Oboama', 'WARD2', 'WARD 5', 'INALENDE AREA', 'Ilupeju Area', 'Shao', 'Lafiagi ward 1', 'Ajanaku', 'Lanwa', 'Ogep', 'Alkaleri west', 'Aisegba Ward 1', 'Gwaram', 'Futuk East', 'Futuk West', 'Soratiyo', 'Polchi', 'Lukshi', 'Kyata', 'Sama', 'Kudu Yamma', 'Kubi A', 'Kariya A', 'Kariya B', 'Rahama', 'Palama', 'Itu ward II', 'Imerienwe', 'Umuoda ward A', 'Ahiara', 'AVU', 'UGBORODO /5', 'OGBE-IJOH /1', 'UBEJI', 'Irette', 'Owere Ebeiri', 'B1', 'C', 'MADANGHO /7', 'OGIDIGBEN', 'Serti Ã¢Â€Â˜BÃ¢Â€Â˜', 'OGIDIGBEN /10', 'IRETE', 'WORKS LAYOUT', 'Makama B', 'Dankade', 'Makama', 'Maji-Dadi A', 'Maji Dadi ', 'Mun', 'Amaifeke', 'Mumsal', 'Birshi', 'Umualum Ward', 'WARD 7', 'ORERE /8', 'Bowen', 'Mowoe', 'Ekurede', 'GBARAMATU /3', 'OGBO-IJO', 'GBARAMATU 3', 'GBARAMATU /4', 'YARKASUWA', 'Okerenkoko', 'Gharamatu 3', 'DABBAN', 'Odekpe Ohita ward', 'Igbudu', 'Obaghoro', 'Ogbudu', 'Ekurede itsekiri', 'Ibilla', 'Oturkpo ward 2', 'Orokam 2', 'Ojigo', 'Otobi', 'Ainu', 'Umuome Umuguma', 'Ehume', 'Nekede', 'Azuzi Ward iv', 'Ikenegbu', 'Amagu Enyigba', 'Orsuihiteukwa', 'Owerre Ebeiri Ward', 'I kenegbu Ward 2', 'Gama', 'Ozara Ward', 'Onitsha north', 'Onitsha North 10', 'Nando1', 'Alushi Ginda', 'Ikka Wangibi', 'Ihiagwa', 'Karau', 'Gallu', 'Mashi', 'Doguru', 'Tsauri A', 'Kurfi A', 'Kurfi B', 'Jigawa', 'OKERE', 'OKUMAGBA 2', 'Agbara', 'Abadiama', 'Darazo', 'DOGURU', 'Doguru B', 'GALLU', 'Okumagba', 'Awkunanaw Ward', 'Uwani Ward', 'Achara Layout', 'Awkunanam Ward', 'Amagugwu 1', 'ASata Ward', 'Achara layout', 'Achaea layout', 'ODUMA WARD 4', 'Okuku', 'NENWE WARD 3', 'NENWE WARD 2', 'MPU Ward 1', 'MPU', 'Edjeba', 'Ajamimogha', 'WARRI', 'EJEGBA', 'OKUMAGBA', 'OGEDEGBE', 'OKUMABGA', 'OGUNU', 'OGBUDU', 'EGBO', 'Yalwa', 'Gano', 'Tsakuwa', 'D/kudu', 'Dawaki', 'Dorawar Sallau HP', 'Garun Malam', 'Kadawa', 'Makwaro', 'Yautar Kudu', 'Karreh', 'ANCHAU', 'Pambeguwa', 'Pamneguwa', 'PAmbeguwa', 'Kwarbai Abubakar', 'Kaura', 'Gora', 'Kwarbai B', 'Kwarbai. A', 'Kwarbai', 'Ungwan Rimi', 'Ung. Gaiya', 'Aungwan Rimi', 'Gidan jatau', 'Gidan Jatau', 'Zango urban', 'Zonzon', 'Ikulu', 'KARREH', 'DAMAU', 'Zonkwa', 'IKENEGBU', 'ESSI LAYOUT', 'Eziobodo', 'Madakiya', 'Ung. Rimi', '***', 'Zaman Dabo', 'Kamantan', 'Zabi', 'Zuntu', 'Kubau', 'Dutsen wai', 'Kargi ', 'Danmaliki', 'Gurun Gawa', 'Naibawa', 'Mariri', 'Kureken sani', 'Zawaciki', 'Danbare', 'Sabongari', 'Darmanawa', 'Gwale', 'Jilawa JaÃ¢Â€Â˜en', 'Sani mainagge', 'Chiranchi', 'Dorayi', 'Sani Mainagge', 'Fagge D2', 'Fagge D1', 'FAgge D2', 'S gari west', 'Kwachiri', 'Kauyen alu', 'U uku cikin gari', 'Babban giji', 'U uku', 'Hotoro ward', 'Gamakai', 'Nasarawa North', 'Ezenei avenue', 'NDEABOH', 'Irele ward 9', 'Nkum Irede', 'Ward 13', 'Gimba', 'Kud III', 'Burdugau', 'Olodan', 'Rubochi', 'Ile-Ogo/Obamoro', 'Richifa', 'Aladinma', 'IKENEGBU ward 1', 'Azuzi ward 1', 'Gyallesu', 'Umuguma', 'Tukur Tukur', 'Kufena', 'Binji', 'EKIUGBO', 'Kangere', 'F1', 'Kinkiba', 'Maigana', 'Soba', 'ward 7', 'ward 9', 'arigidi', 'ifesowopo', 'Makarfi', 'Ijokodo 7', 'Independent Layout', 'Enugu Ward', 'AKWUKE', 'AMANASATO WARD 1', 'AMANASATO WARD 2', 'ODUMA WARD 1', 'ODUMA WARD 2', 'Gwaskwaram', 'Abukur', 'Makurda', 'Kurabau', 'Majen Gobir', 'RIMI', 'Iyatawa', 'Kadandani', 'Umabi', 'Okpatu', 'Ukana awhum', 'Abor', 'Ngwo', 'Okwe', 'Ngwo uno', 'Umuanekeuba ward', 'Opokolo', 'Awlaw', 'Inyi 4', 'Achi Uno 1', 'Achi Uno 2', 'Achi Agu 2', 'Goron Dutse', 'S mainagge', 'Miri ward', 'Yantomo', 'Garin danga', 'Lafiagi', 'GULBIN BOKA', 'Hotoron Arewa', 'Albasu', 'Insharuwa', 'Danja A', 'D/MUSA', 'Olomoore 12', 'Turunku', 'Birnin Yero', 'BARE', 'Rigasa', 'Sabon Gari Allaraini', 'Sabon Birni', 'Inyi 1', 'Gwaraji', 'Zagon Aya', 'Akpakpa 9', 'WURNO', 'Umuhu', 'Kangere ward', 'Ujioelen 4', 'Ketare', 'Olomoore-Ita oshin 12', 'Maduemezia avenue ward 4', 'OGHARA', 'Ogbogonogo ward 5', 'EDJEBA', 'AWIRHE', 'AGBARHA', 'KOZA', 'Onitsha 3', 'Wawar kaza', 'MAI ADUA B', 'MAIKONI A', 'MAIKONI', 'Arewa B', 'Mabai', 'Wakilin Arewa B', 'MAI GAMJI', 'MAZOJI A.', 'MAZOJI B.', 'MATAZU B.', 'DAYI', 'DAN SAKA', 'MUSAWA', 'JIKAMSHI', 'KIRA', 'Jili', 'Balare', 'Chula', 'Ifite Ogwari 1', 'Yamma I', 'Wakilin Gabas I', 'a B', 'Zango', 'OTOVWODO', 'UWHERU', 'EDJEKOTA', 'Uvwie', 'AGADAMA', 'NATSALLE', 'Gangere ward', 'BUMBUM B', 'Wahu', 'Danmaidaki', 'Muchiya', 'Lanzai', 'OVWIAN', 'Galambi', 'Gambar', 'Mwari ', 'Kudu III', 'Galambi ward', 'Miri', 'Garuza', 'Muzuwa ward', 'Garuza Ward', 'Bogo Ward', 'Shango Ward', 'Shango', 'Boi ', 'Tapshin', 'Ashaka magama', 'Ashaka dayayi', 'EWU', 'OGODA', 'EKAKPAMRE WARD', 'UHEREVIE OGHARA', 'OGHAREFE', 'Dadin kowa', 'Balan Kanawa', 'WARD 9', 'JEDDO', 'UGBOKODO', 'UGHOTON', 'Alapere', 'OSUBI', 'OHA', 'OREROKPE', 'UVWIAMUGHE', 'OTERI UGHELLI', 'Bogoro. B', 'UGHELLI', 'ETEFE', 'OGUNAME', 'AKUTE', 'AJUWON', 'Lambe', 'Ifo', 'Oke Aro', 'Bogoro B', 'EWU WARD3', 'WARD 10', 'Ugberiko5', 'UGHELLI WARD 2/6', 'OROGUN WARD 1', 'OROGUN WARD 2', 'Alasa', 'UGHELLI WARD 3/7', 'Bode Sadu', 'UGHELLI WARD 1/5', 'AGBARHA WARD 1', 'Ikwa', 'OROGUN WARD1', 'Lusa D', 'Gabas II', 'WARD 6', 'WARD 4', 'Madadi', 'Nassarawa', 'Batagarawa', 'Zuwo', 'Wawar Kaza', 'Erunkun /ward D', 'Ajiwa ', 'Tadnum/Baram', 'Jafaru', 'Dandagoro', 'Shema', 'Oke - Aro', 'Oke aro', 'MATOGUN', 'Wakilin arewa', 'Gabas ii', 'Kudu ii', 'Kudu iii', 'Wakilin kudu iii', 'Wakilin yamma', 'Dutsinma B', 'Yandoma', 'Ward5', 'Ede-Enu', 'Adiyan', 'Ajuwon', 'UDUERE', 'Romi', 'BUMBUM', 'BUMBUM A', 'Wai A', 'Alapere /ward A', 'Kudu ll', 'Yangora', 'Tama/daye', 'Bindawa', 'Gubuchi', 'Giremawa', 'Gabas ll', 'Yamma ll', 'Gabas l', 'Shinkafi B', 'Kudu lll', 'Umuaka Ward 2', 'Lere north', 'Papa North', 'Papa South', 'Tirwun Kangere', 'Kundum Durum', 'Gurbana', 'Badara', 'Badara East', 'Pali', 'Maimadi', 'Lim', 'Birim', 'Zumbul ', 'Zumbul', 'Ningi East', 'Ilogbo', 'Makami', 'GALADIMA', 'TUDUN WADA', 'Ijoko', 'Kajola okesa', 'TILDE WARD', 'TIYIN', 'Opalo', 'Moore', 'Okerewe 1', 'Okerewe 3', 'Ilode 2', 'ILODE 2', 'Ilare 1', 'Toro', 'Iremo 1', 'Ribina word', 'Ilare 2', 'Ward 5 Owase', 'Yekemi', 'RIBINA WARD', 'Moore ', 'Ilode 1', 'Okerewe', 'Kofar Waika', 'Igbesa', 'Ogungbade', 'Kajola', 'Osiele', 'Iremo 2', 'Ibaregun', 'Pakoto', 'Orile Ifo', 'Asalu Oyetoro', 'Ilepa', 'ITOKI', 'Abule-ijoko', 'Lemode Ijoko', 'Ijoun', 'ABADAWA', 'Ado Odo 2', 'Dadinkowa', 'FALALI', 'Elele', ' SAMINAKA', 'Power line ward', 'Oposuru ward 2', 'Araromi Abule- Iroko', 'Cambel Abule Iroko ward', 'Abule- Iroko Ward', 'Olournshogo ward', 'Folarin Estate Ward', 'Royal Estate ward', 'Folerin Estate Ward', 'Lemode ward', 'Aare ward', 'David Camp ward', 'Ajowa ward', 'SAMINAKA', 'IFO', 'BUNUNU B', 'AGBADO', 'Kauru west', 'BUNUNU', 'Kauru east', 'Gabarin yamma', 'Lere', 'BULA B', 'BUNUNU  B', 'Onyedega', 'Igwebuike', 'Ngwa 1', 'Sango', 'Umueri2', 'GARU', 'TABANNI/YARRADDAU', 'R/SANYI', 'MÃ¢Â€ÂœFASHI', 'M/FASHI', 'KARFI', 'MFASHI', 'Amassoma Ward 11', 'Kangiwa', 'M FASHI', 'BORIN DAWA', 'GAR', 'Kyari', 'Bakin kogi', 'Gabchiyari ward', 'Esuk ewang', 'Urban ward 3', 'Umumukwu', 'Urban 4', 'Ibeku ward 6', 'AJAGBODUDU', 'Ibeku ward 3', 'Word bank', 'world bank', ' 3 urban ', 'Urban ward', 'Ibiaku Ward 2', 'Otoro ward 3', 'Ibialku Ward 2', 'Old express', 'Eziukwu', 'Uratta ward 6', 'Azuokpaja', 'Eziama ward 1', 'Eziama', 'Ovom 1', 'Dan Dango', 'Ikpaibom Ward 4', 'Ujiolen 7', 'Ukpum minya ward 4', 'Mai nika', 'Fagarau', 'Avutu', 'Agbor 1', 'Ogbor Hill 2', 'Ogbor 2', 'Ikpa Ibom Ward 3', 'Ota Ward I', 'Atan Ota Ward', 'Ota Ward II', 'Bakiyawa', 'Child ave', 'Moshalasi', 'Moss', 'Commerical avenue', 'Fatiregun', 'M kalil', 'Herberth macaulay', 'Makoko', 'Dabaibayawa ward', 'Galadanchi', 'Olomoore', 'Ita-Oshin /Olomore 12', 'GARKI', 'M kalik', 'Aguda', 'Opeilu', 'Akpanya', 'Okinni', 'Gbongan Rural/Ward 7', 'Kakau', 'Makera', 'Jiwa', 'Gui', 'Gwarinpa', 'Gurdi', 'Kabusa', 'Kurmin Kogi', 'Jagbe 6', 'Wai B word', 'Wai word', 'Wai A word', 'Bula word', 'Bula A word', 'Dajin word', 'Kimari word', 'Zabi word', 'Isawa word', 'Uzum word', 'Wando word', 'Zurgwai word', 'Boi B ward', 'Kardam word', 'Kardam A word', 'Bogoro B ward', 'Tapshin ward', 'Bogoro C ward', 'Bogoro D ward', 'Bogoro ward', 'Bogoro C', 'Bogoro A ward', 'Unity', 'Bogoro  D ward', 'Jaffa', 'NYANYA', 'Dabaibayawa Ward', 'MAIADUA A', 'Afuze 1', 'Ayetoro Ward', 'Eggua Ward', 'Igan Ilade Ward', 'Oyinbo Igbogila', 'Oja Ijoun Ward', 'Ijoko Ward', 'Ilogbo Ward', 'Iju Ward', 'Ota Ward', 'Kola Tarasa', 'Dagu', 'MURI C', 'Narayi', 'Ibapon-4', 'Gidan waya', 'Godogodo', 'Jagindi', 'Osusu', 'Atuku', 'Aba north', 'Bula A', 'Tirwin', 'TIRWIN', 'Bula', 'Ogore Ito', 'Ota II', 'Ogore', 'Ogege', 'Ekile', 'Burga', 'Idofoi Ward', 'Imasai Ward', 'Ayetoro Awela Ward I', 'Kpambo puri', 'Chanchangi', 'Dull', 'Lusa B ward', 'Lusa B', 'Lusa B word', 'Wai A ward', 'Kardam ward', 'Kardan B ward', 'Boto sadawa ward', 'Boto primary school ward', 'Boto zabir ward', 'Boto nabar ward', 'Wai  word', 'Gayama', 'Jimiya', 'Matogun', 'Basansa', 'Agbelekale Olota', 'Tunfafi', 'Shira', 'Zagun', 'FAGGO B', 'Bidir', 'Kafin kuka', 'Kafin Kuka', 'Madangala', 'Ragwam Magwanshi', 'Ragwam magonshi', 'Chinade', 'Hammaali', 'Fadan Kamantan', 'Madachi/Gangai', 'Madachi', 'Buskuri', 'Bulkachuwa', 'Madachi Gangai', 'Kirchibuwa', 'Madufa', 'Ibite uwani', 'Murmur South', 'Murmur', 'Tashena', 'Gadai', 'Ribina', 'Kandawa/jobe', 'Manomawa/kafi', 'Dara', 'Yaya', 'Bare ruwa/ruruma', 'B/DAWA', 'Yame', 'Fagam', 'Wanka', 'Krifi', 'Dewu ', 'Alkaleri East', 'Akute ', 'Nassarwo', 'Bolari East', 'Pantami', 'Jekadafari', 'Shamaki', 'Ibogun', 'Adiya', 'Olambe', 'OKE ARO', 'Aso /Kodape', 'Shamaki ', 'Kafin Sarkin Yaki', 'Kaltungo east', 'Olugbo', 'Areta', 'Alabata', 'Obantoko', 'Eleweran;Abeokuta', 'Falomo', 'D1', 'Ward 7 dla road', 'Papa-Ajao', 'ONIBUDO', 'Dogon Nini', 'Bunduru', 'Ninzo south', 'Wasa', 'Nando', 'Bunubu', 'Kona', 'Ngbo', 'Jauro Yinnu', 'Gwantu', 'Yelwa', 'Bokana ward', 'Nsndu', 'Ninzo west', 'Arak ', 'Karshi ward', 'WARD 12', 'WARD11', 'Iboko', 'Ejule Allah', 'Ejule allah', 'Ejule', 'WASA', 'Badurum', 'Ujeh', 'Kamaru', 'Oji